INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Major,15','Tarragona','Osacrs','43100');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Gran Via,25','Barcelona','Cineplex','08001');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Calle Mayor,8','Madrid','Cinema Palace','28013');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Rambla Nova,30','Tarragona','Multicines Odeon','43001');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Paseo de Gracia,42','Barcelona','Royal Cinema','08007');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Calle Colón,18','Valencia','Cines Capitol','46004');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Alameda Principal,50','Málaga','Cines Albéniz','29001');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Gran Vía,33','Madrid','Callao City Lights','28013');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Calle Sierpes,12','Sevilla','Cines Avenida','41004');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Ronda Universitat,7','Barcelona','Verdi Park','08007');

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 1',120,1);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 2',120,1);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 3',120,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 1',120,2);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 2',120,2);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 3',120,2);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 1',120,3);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 2',120,3);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 3',120,3);

