-- =============================================
-- CINEMAS (name: 2-110 chars, address: 5-150 chars, city: 2-150 chars, postalCode: 5 dígits)
-- =============================================
INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Carrer Major, 15','Tarragona','Oscars Cinema','43100');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Gran Via, 25','Barcelona','Cineplex','08001');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Calle Mayor, 8','Madrid','Cinema Palace','28013');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Rambla Nova, 30','Tarragona','Multicines Odeon','43001');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Paseo de Gracia, 42','Barcelona','Royal Cinema','08007');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Calle Colón, 18','Valencia','Cines Capitol','46004');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Alameda Principal, 50','Málaga','Cines Albéniz','29001');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Gran Vía, 33','Madrid','Callao City Lights','28013');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Calle Sierpes, 12','Sevilla','Cines Avenida','41004');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Ronda Universitat, 7','Barcelona','Verdi Park','08007');

-- =============================================
-- ROOMS (name: 2-110 chars, capacity: 1-500)
-- =============================================
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 1',120,1);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 2',120,1);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 3',120,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 1',150,2);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 2',100,2);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 3',80,2);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 1',200,3);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 2',180,3);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 3',90,3);

-- =============================================
-- GENRES (initialized at startup)
-- =============================================
INSERT INTO GENRE(ID,NAME) VALUES (1,'Acció');
INSERT INTO GENRE(ID,NAME) VALUES (2,'Aventura');
INSERT INTO GENRE(ID,NAME) VALUES (3,'Comèdia');
INSERT INTO GENRE(ID,NAME) VALUES (4,'Drama');
INSERT INTO GENRE(ID,NAME) VALUES (5,'Thriller');
INSERT INTO GENRE(ID,NAME) VALUES (6,'Ciència ficció');
INSERT INTO GENRE(ID,NAME) VALUES (7,'Romàntica');
INSERT INTO GENRE(ID,NAME) VALUES (8,'Terror');
INSERT INTO GENRE(ID,NAME) VALUES (9,'Animació');
INSERT INTO GENRE(ID,NAME) VALUES (10,'Fantasia');
INSERT INTO GENRE(ID,NAME) VALUES (11,'Documental');
INSERT INTO GENRE(ID,NAME) VALUES (12,'Musical');

-- =============================================
-- MOVIES (title: 2-110 chars, duration: 25-500, description: 10-500 chars, releaseDate: yyyy-MM-dd)
-- Els gèneres s'associen a la taula MOVIE_GENRES
-- =============================================
INSERT INTO MOVIE(TITLE,DURATION,DESCRIPTION,RELEASE_DATE) VALUES
('El Padrino',175,'La historia de la familia Corleone en el mundo de la mafia de Nueva York','1972-03-24');

INSERT INTO MOVIE(TITLE,DURATION,DESCRIPTION,RELEASE_DATE) VALUES
('Inception',148,'Un ladrón que roba secretos corporativos a través de la tecnología de los sueños compartidos','2010-07-16');

INSERT INTO MOVIE(TITLE,DURATION,DESCRIPTION,RELEASE_DATE) VALUES
('Interstellar',169,'Un grupo de exploradores viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad','2014-11-07');

INSERT INTO MOVIE(TITLE,DURATION,DESCRIPTION,RELEASE_DATE) VALUES
('Pulp Fiction',154,'Las vidas de dos mafiosos, un boxeador y una pareja de ladrones se entrelazan en historias de violencia y redención','1994-10-14');

INSERT INTO MOVIE(TITLE,DURATION,DESCRIPTION,RELEASE_DATE) VALUES
('The Dark Knight',152,'Batman se enfrenta al Joker, un criminal que siembra el caos y la destrucción en la ciudad de Gotham','2008-07-18');

INSERT INTO MOVIE(TITLE,DURATION,DESCRIPTION,RELEASE_DATE) VALUES
('Missió Impossible: Sentència Mortal',163,'Ethan Hunt i el seu equip s''enfronten a una nova amenaça tecnològica que pot canviar el destí del món','2023-07-12');

-- =============================================
-- MOVIE_GENRES (associació pel·lícula <-> gèneres)
-- =============================================
-- El Padrino: Drama, Thriller
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (1,4);
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (1,5);
-- Inception: Acció, Ciència ficció, Thriller
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (2,1);
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (2,6);
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (2,5);
-- Interstellar: Aventura, Drama, Ciència ficció
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (3,2);
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (3,4);
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (3,6);
-- Pulp Fiction: Drama, Thriller
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (4,4);
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (4,5);
-- The Dark Knight: Acció, Drama, Thriller
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (5,1);
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (5,4);
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (5,5);
-- Missió Impossible: Sentència Mortal: Acció, Aventura, Thriller
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (6,1);
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (6,2);
INSERT INTO MOVIE_GENRES(MOVIE_ID,GENRE_ID) VALUES (6,5);

-- =============================================
-- SEATS (seatRow: 1-10 chars, number: 1-500, type: Standard/Premium/Adapted, state: true/false)
-- =============================================
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('A',1,0,0,'Standard',true,1);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('A',2,1,0,'Standard',true,1);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('A',3,2,0,'Standard',true,1);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('A',4,3,0,'Premium',true,1);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('A',5,4,0,'Premium',true,1);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('B',1,0,1,'Standard',true,1);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('B',2,1,1,'Standard',true,1);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('B',3,2,1,'Adapted',true,1);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('B',4,3,1,'Standard',true,1);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('B',5,4,1,'Standard',true,1);

INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('A',1,0,0,'Standard',true,2);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('A',2,1,0,'Standard',true,2);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('A',3,2,0,'Premium',true,2);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('B',1,0,1,'Standard',true,2);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('B',2,1,1,'Adapted',true,2);

INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('A',1,0,0,'Standard',true,3);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('A',2,1,0,'Standard',true,3);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('A',3,2,0,'Standard',true,3);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('B',1,0,1,'Premium',true,3);
INSERT INTO SEAT(SEAT_ROW,NUMBER,X,Y,TYPE,STATE,ROOM_ID) VALUES
('B',2,1,1,'Standard',true,3);

-- =============================================
-- SCREENINGS (dateTime: yyyy-MM-dd HH:mm:ss, price, movie, room)
-- =============================================
INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-05-03 18:00:00',8.50,1,1);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-05-10 21:30:00',9.50,1,2);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-05-05 19:15:00',8.00,2,4);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-05-12 20:00:00',10.00,2,5);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-05-07 18:30:00',8.40,3,7);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-05-14 20:00:00',9.00,3,8);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-05-09 19:30:00',8.75,4,3);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-05-16 21:00:00',9.25,4,6);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-05-11 20:15:00',10.00,5,8);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-05-18 18:45:00',7.90,5,9);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-06-02 22:00:00',8.20,1,3);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-06-04 21:30:00',9.80,2,4);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-06-06 18:00:00',8.60,3,7);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-06-08 20:30:00',8.90,4,2);

INSERT INTO SCREENING(DATE_TIME,PRICE,MOVIE_ID,ROOM_ID) VALUES
('2026-06-10 19:00:00',9.10,5,1);

